/*
 * Stoatworks Labs - About window data for Splitflap.
 *
 * PROVISIONAL HAND COPY. In a released repo this file is GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json,
 * and the next sync overwrites it. splitflap is not registered yet, so this
 * is a hand copy adapted from pattern's, with `guide` empty because no user
 * guide exists: StoatworksAboutLinks.h then leaves the guide button out, and
 * the About block is four entries (About text, Project page, Source on
 * GitHub, Support the work). The release step re-generates it.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Splitflap";
    inline constexpr auto slug = "splitflap";
    inline constexpr auto hook = "The picture on a split-flap departures board, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/splitflap/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/splitflap";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
